//
//  ZodiacModel.swift
//  ZodiacApp
//
//  Created by Taylor Ji on 2023-09-30.
//

import UIKit


struct ZodiacData: Hashable{
    var id: Int
    var name: String
    var description: String
    var imageUrl: ImageResource
}

class ZodiacModel: NSObject {
    static let data: [ZodiacData] = [
        ZodiacData(id: 1, name: "Monkey", description: "MONKEY is the ninth sign of the lunar calendar.\nI am the seasoned traveler of the Labyrinth. The genius of alacrity, wizard of the impossible. My brilliance is yet unmatched in its originality. My heart's filled with potent magic that could cast a hundred spells. I am put together for mine own pleasure.\n\nSign of the inventor, improviser and motivator, a charlatan capable of drawing everyone to him with guile and charm\nQuick-witted genius, clever, flexible and innovative\nCan solve intricate problems with ease and is a fast learner, no challenge is too great\nMay have an inborn superiority complex, with a low level of respect for others, or rather, a too-high level of respect for himself\nVery sociable with the ability to get you on his side\nNever lacking confidence, not matter how docile they appear\nNot completely selfish though, more like a child with a delightful preoccupation in himself\nWhen talking to a Monkey, be factual\nFellow “Doers”, the Rat and Dragon, complement Monkeys best. Tigers and Monkeys are not a good mix!", imageUrl: ImageResource.monkey),
        ZodiacData(id: 2, name: "Rooster", description: "ROOSTER is the tenth sign of the lunar calendar.\nI am on hand to herald in the day, and to announce its exit. I thrive by clockwork and precision. In my unending quest for perfection all things will be restored to their rightful place. I am the exacting taskmaster, the ever-watchful administrator. I seek perfect order in my world. I represent unfailing dedication.\n\nThe dauntless hero who must look to the earth to survive, he is the most misunderstood and eccentric of all the signs\nThe epitome of self-assurance and aggression, but at heart can be conservative and old-fashioned\nTypically two rooster types, the rapid-firing, extremely talkative type, and the deadly somber observers- both equally hard to deal with\nAcute, neat, meticulous, organized, decisive, upright, direct and alert\nOutstanding performer that shines when they are the center of attention, could well pursue any career putting them in the public eye\nStick with the Ox and Snake; dedicated fighters- shy away from Rabbit’s!", imageUrl: ImageResource.rooster),
        ZodiacData(id: 3, name: "Dog", description: "DOG is the eleventh sing of the lunar calendar.\nThe martial strains have summoned me to hear your sorrows, still your pain. I am the protector of Justice. Equality, my sole friend. My vision is never blurred by cowardice, my soul never chained. Life without honor is life in vain.\n\nVery likeable, honest, intelligent and straightforward\nDeep sense of loyalty and passion for justice and fair play\nAnimated and attractive, amiable and unpretentious, can get along with others and is not too demanding\nAt times will protect the interests of others more than himself\nAnger can come in bight flashes, but will die quickly too, it will always be justifiable though\nThe Dog was born with his defenses up, you will have to gain their confidence slowly\nWill work hard when he wants to, otherwise has a certain “lie by the fire” laziness\nCan be practical, fearless and the owner of a sharp tongue, unrealistic and outspoken\nThe Dog, Tiger and Horse are united in their quest for idealism, you will find it hard to relax in the presence of the Dragon.", imageUrl: ImageResource.dog),
        ZodiacData(id: 4, name: "Boar", description: "BOAR is the twelfth sign of the lunar calendar.\nOf all God's children I have the purest heart. With innocence and faith, I walk in Love's protective light. By giving of myself freely I am richer and twice blest. Bonded to all mankind by common fellowship, my goodwill is universal and knows no bounds.\n\nThe sign of honesty, simplicity and great fortitude\nGallant, sturdy and courageous, will apply themselves to tasks with all their strength\nMay appear rough on the outside, but beyond the surface is different\nA natural person, the original nice guy, popular and sought after\nSeeks universal harmony, will have fights but will not hold grudges\nEqually known for his wantan pursuit of pleasure- sometimes the saint and sinner can be intertwined\nLoyal and thoughtful, will make lasting and beneficial relationships\nThe boar will grow on you-you cannot do without him!\nWill welcome a friend and their troubles with open arms\nStick with emotionally and artistically guided signs of the Rabbit and Goat- beware the Snake!", imageUrl: ImageResource.pig),
        ZodiacData(id: 5, name: "Rat", description: "RAT is the first sign of the lunar calendar.\nI am a self-proclaimed inquisitor. I am a link yet I function as a complete unit. I aim at encompassing heights and strike my target, sure and steady. \nLife is one joyous journey for me. Each search must end with a new quest. I am progress, exploration and insight. I am the womb of activity.\n\nCharming, innovative and intelligent \nForthright, inquisitive and intrusive but always in a disarmingly honest way \nExcels in business, alert to opportunities \nEasy to get along with, hardworking and thrifty \nGenerous to those you are fond of /nCan be easily agitated but maintains self control, gaining many friends \nBright, fun-loving, social, occasionally critical or grouchy /nFemale rats may be especially frugal, but usually not with their own children \nOverambitious at times \nHang out with Ox, Dragon, Snake, Monkey, you’ll get along well. Tiger, Dog, Boar or another Rat will also \nprovide good company. Avoid Horse, and you may want to steer clear of the Rooster and Goat.", imageUrl: ImageResource.rat),
        ZodiacData(id: 6, name: "Ox", description: "OX is the second sign of the lunar calendar. \nMine is a stabilizing force that perpetuates the cycle of life. I stand immobile against the test of adversity, resolute and unimpeachable. I seek to serve integrity, to the burdens of righteousness. I abide by the laws of nature patiently pushing the wheel of Fate. Thus, I shall weave my own destiny.\n\nSymbolizes the attainment of prosperity through fortitude and hard work\nDependable, calm, methodical \nPatient and tireless worker, sticks to routines and conventions\nGenerally fair-minded and a good listener but difficult to change his mind\nWith affairs of the heart, the Ox can be naïve, not fully comprehending the entrapments of love. Don’t expect poetry and romanticism. They will be inclined to long courtships.\nCharitable by nature, backbone of society\nMay hold grudges for long periods of time\nKnows how to give orders as well as taking them\nStick with the Snake and Rooster, watch out for Goat!", imageUrl: ImageResource.ox),
        ZodiacData(id: 7, name: "Tiger", description: "TIGER is the third sign of the lunar calendar.\nI am a delightful paradox. The entire world is my stage. I set new trails ablaze; I seek the unattainable, and try the untried. I dance to life's music in gay abandon. Come with me on my carousel rides. See the myriad of colors, the flickering lights. All hail the unparalleled performer, me.\n\nSymbolizes power, passion and daring\nA rebellious, colorful and unpredictable character, commanding awe and respect from all quarters\nImpulsive and vivacious, restless and reckless. Loves being the center of attention.\nHas humanitarian instincts, loves babies, endangered species\nWhatever the current object of adulation is, everything else will take second place\nThe tiger can be aspiring and adventurous, trusting their own luck and charisma to see them through tough times and eventually bring successes\nFemale tigers are fashion conscious, articulate and liberated\nMay have large ego, but romantic at heart\nThe Horse and Dog will provide wonderful friendships; Monkey is not a good fit for you!", imageUrl: ImageResource.tiger),
        ZodiacData(id: 8, name: "Rabbit", description: "RABBIT is the fourth sign of the lunar calendar.\nI am in tune with the pulse of the universe. In my quiet solitude I hear the melodies of the soul. I float above commonplace dissent and decay. I am subdued by my ability to conform. I color my world in delicate pastel hues. I epitomize harmony and inner peace.\n\nConsidered very fortunate\nServes as a symbol of longevity, said to derive it’s essence from the moon\nSoul of graciousness, good manners, sound counsel, kindness and sensitivity to beauty\nSoft-spoken, graceful and elegant\nNaturally reserved, artistic and likely to possess good judgment\nLucky in business, thorough and will shine in fields of law, government and research\nCan be cunning, and even ruthless, suave and self-indulgent\nStrong-willed and self-assure, pursuing objectives with methodical precision\nMs. Rabbit is delightful and her company is highly sought after, but when she feels she’s had enough will drop whatever she is doing to rest\nBest Rabbit matches are Goat and Boar- your opposite is the Rooster!", imageUrl: ImageResource.rabbit),
        ZodiacData(id: 9, name: "Dragon", description: "DRAGON is the fifth sign of the lunar calendar.\nI am an unquenchable fire, the center of all energy, the stout heroic heart. I am truth and light, I hold power and glory in my sway. My presence disperses dark clouds. I have been chosen to tame the Fates.\n\nMagnanimous and full of vitality and strength\nConstantly on the go, egoistical and eccentric, dogmatic, whimsical and demanding, but never without and band of admirers\nDragon children tend to assume the burdens and responsibilities of a family\nEnergetic and eager with the potential to accomplish great things. But, if not careful to contain enthusiasm, can burn up in smoke.\nPowerful and difficult to oppose, prosperous, but prone to megalomania and intimidation\nDespite his ways is loyal to friends and family\nDon’t expect a Dragon to be overly sentimental or romantic\nA super positive person\nIt is said that Dragons born during a storm will lead a tempestuous and hazardous life, while those born during calm seas and heavens will live a more protected and amiable life\nDragons, befriend the Rat and Monkey- avoid the Dog.", imageUrl: ImageResource.dragon),
        ZodiacData(id: 10, name: "Snake", description: "SNAKE is the sixth sign of the lunar calendar.\nMine is the wisdom of the ages. I hold the key to the mysteries of life. Casting my seeds on fertile ground, I nurture them with constancy and purpose. My sights are fixed. My gaze remains unchanged. Unyielding, inexorable and deep, I advance with steady gait, the solid earth beneath me.\n\nPhilosopher, theologian, political wizard, wily fancier- the Snake is the deepest thinker and the enigma\nEndowed with a personal wisdom\nGraceful and soft-spoken, will gravitate naturally towards the finer things in life\nVery beautiful\nGenerally relies on their own judgment, not working well with others, trusting their own instincts rather than outside advice\nBy nature is skeptical, but will keep his suspicions to himself\nOne of the most tenacious signs, never stops plotting and can be viciously unrelenting. Can be possessive and demanding in relationships.\nSnake women are the original femme fatale, if she doesn’t have money and power she will marry into it, and won’t agonize over women’s rights. She will be her husbands’ best asset.\nOx and Rooster are your fellow intellectuals; Snake and Boar do not mix well!", imageUrl: ImageResource.snake),
        ZodiacData(id: 11, name: "Horse", description: "HORSE is the seventh sign of the lunar calendar.\nI am the Kaleidoscope of the mind. I impart light, color and perpetual motion. I think, I see, I am moved by electric fluidity. Constant only in my inconstancy, I am unshackled by mundane holds, unchecked by sturdy, binding goals. I run unimpeded through virgin paths. My spirit unconquered, my soul forever free.\n\nCheerful, popular and quick-witted, although can be hot-tempered and headstrong at times\nThe unpredictable horse can fall in and out of love easily\nWarmly appealing, has a love of sports, outdoor activities and animals\nNatives of this sign are often called playboys or playgirls, but is just as skillful in business as in love\nCan be impulsive and stubborn. known for an explosive nature\nThe intelligent horse is performance and success oriented\nQuick to build up speed and quick o lose interest\nThe lady horse is full of spunk\nThe Tiger and Dog are fellow idealists and will provide good relationships, the Rat is its exact opposite.", imageUrl: ImageResource.horse),
        ZodiacData(id: 12, name: "Goat", description: "GOAT is the eighth sign of the lunar calendar.\nI am nature's special child. I trust and am rewarded by trust. Fortune smiles upon my countenance. All things blossom in the gentleness of my love. I strive to find beauty in all I behold. I am fair of face and full of grace.\n\nThe Samaritan, righteous, sincere and easily taken by sob stories\nWell mannered, even shy. Gentle and compassionate.\nAt his best, is artistic, fashionable and creative, worst, is easily overcome by emotions, depressed and withdrawn\nDislikes strict schedules and too much discipline and criticism.\nApt to mother and/or smother its object of affection\nGenerous and containing fantastic luck and fortune\nThe Goat is a worrier and tends to be a pessimist and expects others to cheer him up\nKnack for turning weakness into strength\nWould rather follow others than make decisions, may be criticized for not taking a firm stand when trying to avoid conflicts\nAlso concerned with their senses, Rabbit and Boar will provide allies- beware the Ox!", imageUrl: ImageResource.goat)
    ]

}
